# -*- coding: utf-8 -*-
"""D1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_50fHZRAPOl5Ej0flbrkecT2Bl2tzIG
"""

import time
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import joblib

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

"""# **Download & Merge datasets**"""

nykaa = pd.read_csv("/content/nykaa_campaign_data.csv")
purplle = pd.read_csv("/content/purplle_campaign_data.csv")
tira = pd.read_csv("/content/tira_campaign_data.csv")

print(nykaa.shape)
print(purplle.shape)
print(tira.shape)

nykaa["Brand"] = "Nykaa"
purplle["Brand"] = "Purplle"
tira["Brand"] = "Tira"

df = pd.concat([nykaa, purplle, tira], ignore_index=True)
print(df.shape)
print(df["Brand"].value_counts())

"""# **EDA**"""

df.info()

df.describe()

for col in ["Campaign_Type", "Target_Audience", "Channel_Used", "Language", "Customer_Segment"]:
    print(df[col].value_counts())
    print()

print("Missing values:")
print(df.isnull().sum())
print()
print("Duplicated rows:", df.duplicated().sum())

print(df["ROI"].describe())
print()
print(df.groupby("Campaign_Type")["ROI"].mean().sort_values(ascending=False))
print()
print(df.groupby("Target_Audience")["ROI"].mean().sort_values(ascending=False))

"""# **Visualization**"""

plt.figure(figsize=(10, 7))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

pd.crosstab(df["Target_Audience"], df["Customer_Segment"])

plt.figure(figsize=(8, 5))
sns.histplot(df["ROI"], bins=50, kde=True)
plt.title("ROI Distribution")
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df["Conversions"], bins=50, kde=True)
plt.title("Conversions Distribution")
plt.show()

print("Clicks > Impressions:", (df["Clicks"] > df["Impressions"]).sum())
print("Leads > Clicks:", (df["Leads"] > df["Clicks"]).sum())
print("Conversions > Leads:", (df["Conversions"] > df["Leads"]).sum())

# ensuring the law : ROI = Revenue / (Acquisition_Cost * Conversions) - 1
roi_formula = df["Revenue"] / (df["Acquisition_Cost"] * df["Conversions"]) - 1
diff = (roi_formula - df["ROI"]).abs()

print("Median diff:", diff.median())
print("Exact matches (<0.01):", (diff < 0.01).sum(), "/", len(df))
print("Correlation:", roi_formula.corr(df["ROI"]))

"""these columns (Revenue , Acquisition_Cost , Conversions) can't be used as a feature because of leakage so we changed the target from ROI to Conversions"""

ratio = df["Conversions"] / df["Leads"]
print(ratio.describe())

funnel_cols = ["Impressions", "Clicks", "Leads", "Conversions", "Revenue"]
print()
print(df[funnel_cols].corr())

"""# **Preprocessing**"""

df = df.drop("Campaign_ID", axis=1)

df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df = df.drop("Date", axis=1)

print(df["Year"].value_counts())

channels = ["Facebook", "WhatsApp", "Google", "YouTube", "Instagram", "Email"]

for channel in channels:
    df[channel] = df["Channel_Used"].str.contains(channel, regex=False).astype(int)

df = df.drop("Channel_Used", axis=1)
df.info()

"""# **Target Transformation**"""

df["Conversions_log"] = np.log1p(df["Conversions"])

target_col = "Conversions_log"

features = [
    "Impressions", "Clicks", "Leads",
    "Brand", "Campaign_Type", "Target_Audience", "Language", "Customer_Segment",
    "Duration", "Year", "Month",
    "Facebook", "WhatsApp", "Google", "YouTube", "Instagram", "Email",
]

X = df[features]
y = df[target_col]
y_original = df["Conversions"]

print(X.shape, y.shape)

"""# **Encoding & Scaling**"""

categorical_features = [
    "Brand", "Campaign_Type", "Target_Audience", "Language", "Customer_Segment"
]

numerical_features = [
    "Impressions", "Clicks", "Leads",
    "Duration", "Year", "Month",
    "Facebook", "WhatsApp", "Google", "YouTube", "Instagram", "Email",
]

preprocessor_scaled = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", StandardScaler(), numerical_features),
    ]
)

preprocessor_plain = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ],
    remainder="passthrough"
)

"""# **Modeling**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

y_train_original = y_original.loc[y_train.index]
y_test_original = y_original.loc[y_test.index]

print(X_train.shape, X_test.shape)

models = {
    "Baseline (Mean)": Pipeline([
        ("prep", preprocessor_plain),
        ("model", DummyRegressor(strategy="mean"))
    ]),
    "Ridge Regression": Pipeline([
        ("prep", preprocessor_scaled),
        ("model", Ridge(alpha=10))
    ]),
    "Decision Tree": Pipeline([
        ("prep", preprocessor_plain),
        ("model", DecisionTreeRegressor(
            max_depth=8, min_samples_leaf=5, random_state=42
        ))
    ]),
    "Random Forest": Pipeline([
        ("prep", preprocessor_plain),
        ("model", RandomForestRegressor(
            n_estimators=100, max_depth=12, min_samples_leaf=2,
            random_state=42, n_jobs=-1
        ))
    ]),
}

print("Models:", list(models))

"""# **Training & Prediction**"""

trained_models = {}
predictions_log = {}
cv_scores_all = {}
training_times = {}

for name, pipe in models.items():
    print(f"Training {name}...")
    start = time.time()

    pipe.fit(X_train, y_train)
    training_times[name] = time.time() - start

    predictions_log[name] = pipe.predict(X_test)
    cv_scores_all[name] = cross_val_score(pipe, X_train, y_train, cv=5, scoring="r2", n_jobs=-1)

    trained_models[name] = pipe
    print(f"  done in {training_times[name]:.1f}s")

"""# **Evaluation & Comparison**"""

results = []

for name in models:
    y_pred_original = np.expm1(predictions_log[name])

    results.append({
        "Model": name,
        "RMSE": np.sqrt(mean_squared_error(y_test_original, y_pred_original)),
        "MAE": mean_absolute_error(y_test_original, y_pred_original),
        "R2 Score": r2_score(y_test_original, y_pred_original),
        "CV R2 (mean, log-scale)": cv_scores_all[name].mean(),
        "CV R2 (std, log-scale)": cv_scores_all[name].std(),
        "Training Time (s)": training_times[name],
    })

results_df = pd.DataFrame(results).sort_values("R2 Score", ascending=False).reset_index(drop=True)
results_df.round(4)

"""# **Choosing the best model**"""

best_name = results_df.iloc[0]["Model"]
best_pipe = trained_models[best_name]

print(f"Best model: {best_name}")
results_df

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].bar(results_df["Model"], results_df["MAE"], color="skyblue")
axes[0].set_title("MAE Comparison (Lower is Better)")
axes[0].tick_params(axis="x", rotation=30)

axes[1].bar(results_df["Model"], results_df["RMSE"], color="salmon")
axes[1].set_title("RMSE Comparison (Lower is Better)")
axes[1].tick_params(axis="x", rotation=30)

axes[2].bar(results_df["Model"], results_df["R2 Score"], color="lightgreen")
axes[2].set_title("R2 Score Comparison (Higher is Better)")
axes[2].tick_params(axis="x", rotation=30)

plt.tight_layout()
plt.show()

cv_df = pd.DataFrame({name: scores for name, scores in cv_scores_all.items() if name != "Baseline (Mean)"})

plt.figure(figsize=(8, 5))
cv_df.boxplot()
plt.ylabel("R2 Score (log-scale)")
plt.title("Cross-Validation R2 Stability")
plt.show()

"""# **Actual vs Predicted**"""

fig, axes = plt.subplots(1, len(trained_models), figsize=(20, 5))

for ax, name in zip(axes, models):
    y_pred_original = np.expm1(predictions_log[name])

    ax.scatter(y_test_original, y_pred_original, alpha=0.2, s=8)
    ax.plot([y_test_original.min(), y_test_original.max()],
            [y_test_original.min(), y_test_original.max()], "r--")
    ax.set_title(name)
    ax.set_xlabel("Actual Conversions")
    ax.set_ylabel("Predicted Conversions")

plt.tight_layout()
plt.show()

"""# **Residuals analysis**"""

fig, axes = plt.subplots(1, len(trained_models), figsize=(20, 4))

for ax, name in zip(axes, models):
    y_pred_original = np.expm1(predictions_log[name])
    residuals = y_test_original - y_pred_original

    ax.scatter(y_pred_original, residuals, alpha=0.2, s=8)
    ax.axhline(0, color="red", linestyle="--")
    ax.set_title(name)
    ax.set_xlabel("Predicted Conversions")
    ax.set_ylabel("Residual")

plt.tight_layout()
plt.show()

"""# **Feature Importance**"""

feature_names = best_pipe.named_steps["prep"].get_feature_names_out()

if hasattr(best_pipe.named_steps["model"], "feature_importances_"):
    importances = best_pipe.named_steps["model"].feature_importances_
    imp_df = pd.DataFrame({"Feature": feature_names, "Importance": importances})
elif hasattr(best_pipe.named_steps["model"], "coef_"):
    importances = best_pipe.named_steps["model"].coef_
    imp_df = pd.DataFrame({"Feature": feature_names, "Importance": np.abs(importances)})

imp_df = imp_df.sort_values("Importance", ascending=False).head(15)

plt.figure(figsize=(9, 6))
sns.barplot(data=imp_df, x="Importance", y="Feature")
plt.title(f"Top 15 Features - {best_name}")
plt.tight_layout()
plt.show()

imp_df

joblib.dump(best_pipe, 'regression_model.pkl', compress=7)