# -*- coding: utf-8 -*-
"""D2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ez1XPt1U2_jJ24upjJ1y9MRi3KqtoVIP

# Digital Marketing — Conversion Classification
"""

import pandas as pd
import numpy as np
import joblib
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc


from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    roc_auc_score, classification_report, ConfusionMatrixDisplay,
)

RANDOM_STATE = 42
sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)

"""## 1) Exploratory Data Analysis"""

import pandas as pd

df = pd.read_csv('/content/digital_marketing_campaign_dataset.csv')
df.head(20)

df['AdvertisingPlatform'].value_counts()

print("Shape:", df.shape)
df.info()

print("Missing values per column:")
print(df.isnull().sum())

print("\nNumber of duplicate rows:", df.duplicated().sum())

df.describe()

df['Gender'].value_counts()

df['CampaignChannel'].value_counts()

df['CampaignType'].value_counts()

conversion_counts = df['Conversion'].value_counts()
conversion_percentages = df['Conversion'].value_counts(normalize=True) * 100

print(conversion_counts)
print(conversion_percentages)

df.groupby('Conversion')['ConversionRate'].describe()

for col in ['Gender', 'CampaignChannel', 'CampaignType']:
    print(f"--- {col} ---")
    print(df.groupby(col)['Conversion'].mean().sort_values(ascending=False))
    print()

conversion_pct = df["Conversion"].value_counts(normalize=True).mul(100).round(2)
print(df["Conversion"].value_counts())
print(conversion_pct)

conversion_pct.plot(kind="bar", title="Conversion Distribution (%)")
plt.show()

numeric_cols = [
    "Age", "Income", "AdSpend", "ClickThroughRate", "ConversionRate",
    "WebsiteVisits", "PagesPerVisit", "TimeOnSite", "SocialShares",
    "EmailOpens", "EmailClicks", "PreviousPurchases", "LoyaltyPoints",
]

for col in numeric_cols:
    q1, q3 = df[col].quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    n_outliers = df[(df[col] < lower) | (df[col] > upper)].shape[0]
    print(f"{col}: {n_outliers} outliers (bounds: {lower:.2f} to {upper:.2f})")

plt.figure(figsize=(14, 10))
sns.heatmap(df[numeric_cols + ["Conversion"]].corr(), annot=True, fmt=".2f", cmap="coolwarm", center=0)
plt.title("Correlation Matrix")
plt.show()

print("EmailClicks > EmailOpens:", (df["EmailClicks"] > df["EmailOpens"]).sum())

"""## 2) Preprocessing"""

ID_COLUMNS = ["CustomerID"]
ZERO_VARIANCE_COLUMNS = ["AdvertisingPlatform", "AdvertisingTool"]

X = df.drop(columns=["Conversion"] + ID_COLUMNS + ZERO_VARIANCE_COLUMNS)
y = df["Conversion"]

X["Gender"] = X["Gender"].map({"Male": 1, "Female": 0})
X = pd.get_dummies(X, columns=["CampaignChannel", "CampaignType"], drop_first=True)

print("X shape:", X.shape)
X.head(20)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)
print("X_train:", X_train.shape, "| X_test:", X_test.shape)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("Scaled shape:", X_train_scaled.shape)

"""## 3) Modeling"""

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=1000, class_weight="balanced", random_state=RANDOM_STATE
    ),
    "Decision Tree": DecisionTreeClassifier(
        max_depth=8, min_samples_leaf=5, class_weight="balanced", random_state=RANDOM_STATE
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=200, max_depth=14, min_samples_leaf=2,
        class_weight="balanced", random_state=RANDOM_STATE
    ),
    "SVM": SVC(
        probability=True, class_weight="balanced", random_state=RANDOM_STATE
    ),
}
print("Models:", list(models))

results = []
trained_models = {}

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    y_prob = model.predict_proba(X_test_scaled)[:, 1]

    cv_f1 = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring="f1").mean()

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred, zero_division=0),
        "Recall": recall_score(y_test, y_pred, zero_division=0),
        "F1 Score": f1_score(y_test, y_pred, zero_division=0),
        "ROC-AUC": roc_auc_score(y_test, y_prob),
        "CV F1": cv_f1,
    })
    trained_models[name] = model

print("All models trained ")

"""## 4) Model Comparison"""

results_df = pd.DataFrame(results).sort_values("F1 Score", ascending=False).reset_index(drop=True)
results_df.round(4)

name = "Logistic Regression"
y_pred = trained_models[name].predict(X_test_scaled)
print(name)
print("=" * 60)
print(classification_report(y_test, y_pred, zero_division=0))

name = "Decision Tree"
y_pred = trained_models[name].predict(X_test_scaled)
print(name)
print("=" * 60)
print(classification_report(y_test, y_pred, zero_division=0))

name = "Random Forest"
y_pred = trained_models[name].predict(X_test_scaled)
print(name)
print("=" * 60)
print(classification_report(y_test, y_pred, zero_division=0))

name = "SVM"
y_pred = trained_models[name].predict(X_test_scaled)
print(name)
print("=" * 60)
print(classification_report(y_test, y_pred, zero_division=0))

results = []

for name, model in trained_models.items():
    y_pred = model.predict(X_test_scaled)

    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test_scaled)[:, 1]
    else:
        y_proba = model.decision_function(X_test_scaled)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, zero_division=0)
    rec = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)

    fpr, tpr, _ = roc_curve(y_test, y_proba)
    roc_auc = auc(fpr, tpr)

    results.append(
        {
            "Model": name,
            "Accuracy": acc,
            "Precision": prec,
            "Recall": rec,
            "F1-Score": f1,
            "ROC-AUC": roc_auc,
        }
    )

comparison_df = pd.DataFrame(results)
comparison_df

from sklearn.metrics import confusion_matrix

fig, axes = plt.subplots(1, 4, figsize=(18, 4))

for idx, (name, model) in enumerate(trained_models.items()):
    y_pred = model.predict(X_test_scaled)
    cm = confusion_matrix(y_test, y_pred)

    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        cmap='Blues',
        ax=axes[idx],
        cbar=False,
        xticklabels=['0', '1'],
        yticklabels=['0', '1']
    )

    axes[idx].set_title(name, fontsize=12, fontweight='bold')
    axes[idx].set_xlabel('Predicted Label')
    axes[idx].set_ylabel('True Label')

plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 6))

for name, model in trained_models.items():
    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test_scaled)[:, 1]
    else:
        y_proba = model.decision_function(X_test_scaled)

    fpr, tpr, _ = roc_curve(y_test, y_proba)
    roc_auc = auc(fpr, tpr)

    plt.plot(fpr, tpr, label=f'{name} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random Chance')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

import joblib

best_model_name = comparison_df.sort_values(
    by=['F1-Score', 'ROC-AUC'], ascending=False
).iloc[0]['Model']

best_model = trained_models[best_model_name]

print(f'Best Model Selected: {best_model_name}')

joblib.dump(best_model, 'best_model.pkl')

joblib.dump(scaler, 'scaler.pkl')